### ISSUE TITLE
Add Unit Tests for main.py Function

### ISSUE THREAD

**Issue by Dhruvnotfound** [Dhruvnotfound/trick-o-truth-discord-bot#2]
Description: The main.py function currently lacks unit tests, which makes it difficult to ensure the correctness of its logic and behavior during updates or refactoring. We need to implement comprehensive unit tests to improve code quality and maintainability.

Tasks:

- Identify key functions and logic in main.py.
- Write unit tests for the primary functions, covering both positive and negative scenarios.
- Ensure edge cases are tested.
- Verify test coverage using a tool like pytest-cov or coverage.py to ensure that all significant code paths are tested.
- Include setup/teardown as needed to handle dependencies or initialization.

Acceptance Criteria:

- [ ] Unit tests are written for all key functions in main.py.

 - [ ] Test coverage should be at least 90%.

**Comment by Kaif9999** [comment]
bro @Dhruvnotfound I am forking this repository adding unit-tests for main.py and will raise a PR soon please accept my request and merge the PR when possible

**Comment by Dhruvnotfound** [comment]
> bro @Dhruvnotfound I am forking this repository adding unit-tests for main.py and will raise a PR soon please accept my request and merge the PR when possible

@rajatkriplani is already working on it
